apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/data"